
    <div class="left-indent">

        <h1>Welcome to ABC Accounting Online Client Notification Manager</h1>
        <div class="centered">
            <form class="form" method="post" action="<?php echo htmlspecialchars('?page=home&action=login'); ?>">

                <div>
                <label for="username">Username</label>
                <input id="username" type="text" name="username" value="barrington<?php //echo @$_POST['username']; ?>">
                </div>

                <div>
                <label for="password">Password</label>
                <input id="password" type="password" name="password" value="test">
                </div>

                <input type="submit" value="Login">
            </form>
        </div>

    </div>