

<div class="left-indent">
    <div class="sub-menu1">
        <ul>
            <li><a href="?page=notification&action=view">View Notifications</a></li>
            <li><a href="?page=notification&action=add">Add Notification</a></li>
            <li><a href="?page=notification&action=view">Archive Notification</a></li> <!--change the action on this button later -->
            <li><a href="?page=notification&action=search">Search</a></li>
        </ul>
    </div>
</div>