
    <div class="left-indent">
        <h1>Backup Database</h1>
        <br>
        <h3><?php echo $message; ?></h3><br><br>


        <div class="left-indent">
            <div class="sub-menu1">
                <ul>
                    <li><a href="dbBackup_ABC.sql" download>Download backup</a></li>
                    <li><a href="?page=user&action=menu">Go Back</a></li>
                </ul>
            </div>
        </div>

    </div>