

<div class="left-indent">
    <h1>Add User</h1>
    <br>
    <p class="required">*Required Field</p><br>

    <form class="form" method="post" action="<?php echo htmlspecialchars('?page=user&action=update') .'&id='. @$currInfo[0]?>">

        <div>
            <?php
            $selected = $currInfo[7];
            if(@$check == 'true'){
                $selected = @$_POST['position'];
            }
            ?>
            <label for="position">Position</label>
            <select id="position" name="position">
                <option value="Manager"<?php echo ($selected == 'Manager')? 'selected': ''?>>Manger</option>
                <option value="Senior Accountant" <?php echo ($selected == 'Senior Accountant')? 'selected': ''?>>Senior Accountant</option>
                <option value="Junior Accountant" <?php echo ($selected == 'Junior Accountant')? 'selected': ''?>>Junior Accountant</option>
                <option value="Chartered Accountant" <?php echo ($selected == 'Chartered Accountant')? 'selected': ''?>>Chartered Accountant</option>
                <option value="Book Keeper" <?php echo ($selected == 'Book Keeper')? 'selected': ''?>>Book Keeper</option>
            </select>
        </div>

        <div>
            <label for="fname">First Name</label>
            <input type="text" name="fname" id="fname" value="<?php echo (@$check =='true')? @$_POST['fname'] : $currInfo[1]; ?>">
            <span class="required">* <?php echo @$errorMsg[0]; ?></span>

        </div>

        <div>
            <label for="lname">Last Name</label>
            <input type="text" name="lname" id="lname" value="<?php echo (@$check =='true')? @$_POST['lname'] : $currInfo[2];?>">
            <span class="required">* <?php echo @$errorMsg[1]; ?></span>
        </div>

        <div>
            <label for="email">Email</label>
            <input type="text" name="email" id="email" value="<?php echo (@$check =='true')? @$_POST['email'] : $currInfo[3];?>">
            <span class="required">* <?php echo @$errorMsg[2]; ?></span>
        </div>

        <div>
            <label for="phone">Phone</label>
            <input type="tel" name="phone" id="phone" value="<?php echo (@$check =='true')? @$_POST['phone'] : $currInfo[4];?>">
            <span class="required">* <?php echo @$errorMsg[3]; ?></span>
        </div>

        <div>
            <label for="username">Username</label>
            <input type="text" name="username" id="username" value="<?php echo (@$check =='true')? @$_POST['username'] : $currInfo[5];?>">
            <span class="required">* <?php echo @$errorMsg[4]; ?></span>
        </div>

        <div>
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <span class="required">* <?php echo @$errorMsg[5]; ?></span>
        </div>

        <div>
            <label for="passConfirm">Password Confirm</label>
            <input type="password" name="passConfirm" id="passConfirm">
            <span class="required">* <?php echo @$errorMsg[6]; ?></span>
        </div>

        <input type="hidden" name="submitCheck" value="true">
        <input type="submit">
    </form>

</div>

