

<div class="left-indent">
    <div class="sub-menu1">
        <ul>
            <li><a href="?page=user&action=view">View Users</a></li>
            <li><a href="?page=user&action=add">Add User</a></li>
            <li><a href="?page=user&action=view">Archive User</a></li>
            <li><a href="?page=user&action=search">Search User</a></li>
            <li><a href="?page=user&action=backup">Database Backup</a></li>
            <li><a href="?page=user&action=restore">Database Restore</a></li>
        </ul>
    </div>
</div>