

<div class="left-indent">
    <div class="sub-menu1">
        <ul>
            <li><a href="?page=client&action=view">View Clients</a></li>
            <li><a href="?page=client&action=add">Add Client</a></li>
            <li><a href="?page=client&action=view">Archive Client</a></li> <!--change the action on this button later -->
            <li><a href="?page=client&action=search">Search</a></li>
        </ul>
    </div>
</div>