

<div class="left-indent">
    <h1>Update Client</h1>
    <br>
    <p class="required">*Required Field</p><br>
    <form class="form" method="post" action="<?php echo htmlspecialchars('?page=client&action=update') . '&id=' . $line[0]?>">

        <div>
        <label for="company_name">Company Name</label>
        <input type="text" name="company_name" id="company_name" value="<?php echo ($check =='true') ? @$_POST['company_name'] : $line[1]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[0]; ?>
        </div>

        <div>
        <label for="contact_fname">Contact First Name</label>
        <input type="text" name="contact_fname" id="contact_fname" value="<?php echo ($check =='true') ? @$_POST['contact_fname'] : $line[2]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[1]; ?>
        </div>

        <div>
        <label for="contact_lname">Contact Last Name</label>
        <input type="text" name="contact_lname" id="contact_lname" value="<?php echo ($check =='true') ? @$_POST['contact_lname'] : $line[3]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[2]; ?>
        </div>

        <div>
        <label for="company_phone">Main Phone</label>
        <input type="tel" name="company_phone" id="company_phone" value="<?php echo ($check =='true') ? @$_POST['company_phone'] : $line[4]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[3]; ?>
        </div>

        <div>
        <label for="company_cell">Cell Phone</label>
        <input type="tel" name="company_cell" id="company_cell" value="<?php echo ($check =='true') ? @$_POST['company_cell'] : $line[5]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[4]; ?>
        </div>

        <div>
        <label for="company_email">Email Address</label>
        <input type="text" name="company_email" id="company_email" value="<?php echo ($check =='true') ? @$_POST['company_email'] : $line[6]; ?>">
        <span class="required">*</span> <?php echo @$errorMsg[5]; ?>
        </div>

        <div>
        <label for="website">Website</label>
        <input type="text" name="website" id="website" value="<?php echo ($check =='true') ? @$_POST['website'] : $line[7]; ?>">
        <span><?php echo @$errorMsg[6]; ?></span>
        </div>

        <input type="hidden" name="submitCheck" value="true">
        <input type="submit" value="Update">
    </form>
</div>