

<div class="left-indent">
    <div class="sub-menu1">
        <h3>Are you sure you would like to archive this client notification?</h3>
        <br>
        <ul>
            <li><a href="?page=client-notification&action=viewNoteByClient&id=<?php echo getParam('cid')?> ">Cancel</a></li>
            <li><a href="?page=client-notification&action=commit-archive&id=<?php echo $id.'&cid='.getParam('cid') ?>">Yes, archive client notification</a></li>
        </ul>
    </div>

</div>